languageCode = "en"
languageName = "English"
weight = 1
title = "WOLF AND CROW"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
logo = "Designer-3-removebg-preview.png"
secondaryLogo = "Designer-removebg-preview.png"
description = "Web Hosting, Tech Support, and Computer Repair"

[author]
name = "WOLF AND CROW"
headline = "Services That Work For You"
bio = "Working in the Tech Industry for over 10 years"
image = "Designer-4-removebg-preview-2.png"
