[[main]]
none = "none"

[[main]]
none = "none"

[[main]]
none = "none"

[[main]]
none = "none"

[[main]]
none = "none"

[[main]]
none = "none"

[[main]]
none = "none"

[[main]]
none = "none"

[[main]]
name = "Services"
pre = "fire"
pageRef = "Services"
identifier = "BLS6p7mj2K"
weight = 1

[[main]]
name = "Kahiko"
pre = "hashnode"
url = "https://kahiko.store"
identifier = "cyg9QcbBJc"
weight = 2

[[main]]
name = "About"
pre = "eye"
pageRef = "About"
identifier = "bS3lNthRS8"
weight = 3

[[footer]]
none = "none"
